[package]
name        = "ferogram-mtproto"
description = "MTProto 2.0 session management, message framing, DH key exchange and transport abstractions"
readme      = "README.md"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
authors.workspace    = true
repository.workspace = true
homepage.workspace   = true
documentation = "https://docs.rs/ferogram-mtproto"
keywords      = ["telegram", "mtproto", "session", "transport", "crypto"]
categories    = ["network-programming", "api-bindings"]

[dependencies]
ferogram-tl-types = { workspace = true, features = ["tl-mtproto"] }
ferogram-crypto   = { workspace = true }
num-bigint = "0.5.1"
sha1       = "0.11.0"
tracing    = { version = "0.1" }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo-machete]
ignored = ["sha1"] # used only inside the ferogram_crypto::sha1! macro expansion
