[package]
name        = "ferogram-connect"
description = "Raw TCP connection, MTProto framing and transport for ferogram"
version.workspace   = true
edition.workspace   = true
license.workspace   = true
authors.workspace   = true
repository.workspace = true
homepage.workspace  = true

[dependencies]
ferogram-tl-types = { workspace = true, features = ["tl-mtproto"] }
ferogram-mtproto  = { workspace = true }
ferogram-crypto   = { workspace = true }
tokio       = { version = "1.23.1", features = ["net", "io-util", "sync", "time", "rt"] }
tokio-socks = { version = "0.5", optional = true }
flate2      = "1"
tracing     = { version = "0.1" }
socket2     = "0.6.0"

[features]
default = []
## SOCKS5 proxy support for outgoing connections. Pulls in tokio-socks.
## Off by default; not needed for direct connections to Telegram datacenters.
socks5 = ["dep:tokio-socks"]

[[bin]]
name = "connect"
path = "src/bin/connect.rs"
