// Copyright (c) Ankit Chaubey <ankitchaubey.dev@gmail.com>
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// ferogram: async Telegram MTProto client in Rust
// https://github.com/ankit-chaubey/ferogram
//
//
// If you use or modify this code, keep this notice at the top of your file
// and include the LICENSE-MIT or LICENSE-APACHE file from this repository:
// https://github.com/ankit-chaubey/ferogram

//! This module is entirely auto-generated by `build.rs`.
//! Do not edit: changes will be overwritten on the next build.

include!(concat!(env!("OUT_DIR"), "/generated_common.rs"));
include!(concat!(env!("OUT_DIR"), "/generated_types.rs"));
include!(concat!(env!("OUT_DIR"), "/generated_functions.rs"));
include!(concat!(env!("OUT_DIR"), "/generated_enums.rs"));
